version: "3.8"

services:
  app:
    build:
        context: ./
        dockerfile: ./builds/nodejs.Dockerfile
    restart: always
    ports:
      - "${APP}:3000"
    volumes: 
      - ./src:/usr/app
      - node_modules:/usr/data
    networks: 
      - rede
    depends_on:
      - mysql
      - phpmyadmin

  mysql:
      image: mysql:5.7.35
      volumes: 
        - db_data:/var/lib/mysql
      restart: always
      networks: 
        - rede
      environment:
        MYSQL_ROOT_PASSWORD: "root"

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports: 
      - "${PHPMYADMIN}:80"
    networks: 
      - rede
    depends_on: 
      - mysql
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "root"
      PMA_PASSWORD: "root"

volumes: 
  db_data:
  node_modules:

networks: 
  rede: